"""web

Revision ID: a776d81302b0
Revises: 394356e215cb
Create Date: 2023-01-16 17:22:53.771267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a776d81302b0'
down_revision = '394356e215cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.drop_index('ix_user_emil')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_column('emil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emil', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_emil', ['emil'], unique=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
